name: Generate Video with VEO3

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Enter the video prompt (cinematic, safe, romantic, etc.)"
        required: true
        default: "A cinematic romantic scene with a couple in their 30s, emotional and intimate but safe"

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-genai pillow

      - name: Run video generation script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          VIDEO_PROMPT: ${{ github.event.inputs.prompt }}
        run: |
          python video_gen.py

      - name: Upload generated videos
        uses: actions/upload-artifact@v4
        with:
          name: generated-videos
          path: |
            video_*.mp4
